---
# tasks file for roles/deploy_app_files
- name: copy static index.html to tomcat webapps/ROOT/index.html
  template:
    src: 'index.html.app{{index+1}}'
    dest: /usr/share/tomcat/webapps/ROOT/index.html
  loop: "{{ groups['apps'] }}"
  loop_control:
    index_var: index
