---
# tasks file for roles/deploy_haproxy
- name: install httpie
  package:
    name: httpie
    state: latest
- name: install haproxy
  yum:
    name: haproxy 
    state: latest
- name: start haproxy
  service:
    name: haproxy
    state: started
- name: configure haproxy
  template:
    src: "{{haproxy_config_src}}"
    dest: "{{haproxy_config_dest}}"
  notify: restart haproxy
